In [1]:
#Import needed libraries
import pandas as pd

In [2]:
#Define locations of datafiles using glob 
zillow_data = ('resources/Zillow_Data/County_Zhvi_AllHomes.csv')

In [3]:
df_zillow = pd.read_csv(zillow_data, encoding="ISO-8859-1")

In [4]:
df_zillow.head()

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,FIPS,SizeRank,1996-04,1996-05,...,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09
0,3101,Los Angeles County,CA,Los Angeles-Long Beach-Anaheim,6,37,6037,1,160800.0,160700.0,...,619600,622100,624000,623500,622100,621800,621200,620900,622300,624900
1,139,Cook County,IL,Chicago-Naperville-Elgin,17,31,17031,2,133400.0,134300.0,...,223300,224000,225400,226600,226200,224900,224000,223500,223200,223300
2,1090,Harris County,TX,Houston-The Woodlands-Sugar Land,48,201,48201,3,97900.0,97800.0,...,188300,189600,191200,191500,190700,190500,191700,192800,193300,193800
3,2402,Maricopa County,AZ,Phoenix-Mesa-Scottsdale,4,13,4013,4,108500.0,108900.0,...,270600,272300,273800,274300,274500,274900,274700,275300,277200,278800
4,2841,San Diego County,CA,San Diego-Carlsbad,6,73,6073,5,163800.0,163400.0,...,593100,592700,592700,592700,593200,593300,593000,592900,593000,593700

In [5]:
#Remove years not between 2009 and 2018

yr = '1996'
while int(yr) < 2009:
    df_zillow = df_zillow.drop(df_zillow.filter(like=yr), axis=1)
    yr=str(int(yr)+1)
    
df_zillow = df_zillow.drop(df_zillow.filter(like='2019'), axis=1)
df_zillow['FIPS'] = df_zillow['FIPS'].apply(lambda x: '{0:0>5}'.format(x))
df_zillow

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,FIPS,SizeRank,2009-01,2009-02,...,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12
0,3101,Los Angeles County,CA,Los Angeles-Long Beach-Anaheim,6,37,06037,1,413700.0,409300.0,...,603900,604700,605300,606600,607800,609400,611700,615200,617900,619600
1,139,Cook County,IL,Chicago-Naperville-Elgin,17,31,17031,2,226000.0,223100.0,...,219500,220000,220700,221000,220900,221100,221700,222200,222800,223300
2,1090,Harris County,TX,Houston-The Woodlands-Sugar Land,48,201,48201,3,132000.0,131700.0,...,180900,181900,182800,183200,183700,184500,185500,186300,187200,188300
3,2402,Maricopa County,AZ,Phoenix-Mesa-Scottsdale,4,13,04013,4,189000.0,185100.0,...,257100,258500,260100,261600,263000,264200,265500,267400,269200,270600
4,2841,San Diego County,CA,San Diego-Carlsbad,6,73,06073,5,388600.0,385200.0,...,582600,583300,583000,583300,585000,588000,590300,591900,593000,593100
5,1286,Orange County,CA,Los Angeles-Long Beach-Anaheim,6,59,06059,6,510700.0,507500.0,...,707500,709100,712200,715900,719300,722500,723300,724300,726100,728000
6,581,Kings County,NY,New York-Newark-Jersey City,36,47,36047,7,491500.0,487300.0,...,773400,777400,780500,782500,783200,783100,784300,786300,786300,783600
7,2964,Miami-Dade County,FL,Miami-Fort Lauderdale-West Palm Beach,12,86,12086,8,211000.0,203400.0,...,288600,290200,292200,294400,296100,297200,298300,300300,302300,304100
8,978,Dallas County,TX,Dallas-Fort Worth-Arlington,48,113,48113,9,121900.0,121600.0,...,190800,192500,194600,196500,198100,199500,200700,202300,205100,209200
9,1347,Queens County,NY,New York-Newark-Jersey City,36,81,36081,10,444900.0,441000.0,...,617800,623100,628900,633300,635600,636200,638600,642300,644900,646100
10,2832,Riverside County,CA,Riverside-San Bernardino-Ontario,6,65,06065,11,246500.0,240500.0,...,367200,367700,369200,371600,374300,377100,378400,377200,376600,378100
11,3250,San Bernardino County,CA,Riverside-San Bernardino-Ontario,6,71,06071,12,221800.0,215700.0,...,332700,334500,336900,339400,341600,343000,343400,343800,345300,346800
12,445,Clark County,NV,Las Vegas-Henderson-Paradise,32,3,32003,13,189600.0,184200.0,...,255300,257000,259800,262600,265600,269400,273300,276400,278800,279800
13,207,King County,WA,Seattle-Tacoma-Bellevue,53,33,53033,14,382000.0,377500.0,...,625300,625500,628700,630600,628900,627700,628400,627100,624600,623700
14,791,Wayne County,MI,Detroit-Warren-Dearborn,26,163,26163,15,71800.0,69100.0,...,70100,71700,73200,73900,74600,75600,76700,78000,79400,80300
15,2049,Tarrant County,TX,Dallas-Fort Worth-Arlington,48,439,48439,16,132800.0,132700.0,...,198300,199200,200400,201800,203100,204100,205400,207500,209600,211700
16,3136,Santa Clara County,CA,San Jose-Sunnyvale-Santa Clara,6,85,06085,17,626800.0,620300.0,...,1243600,1259600,1281100,1297500,1300500,1299400,1301500,1299200,1287200,1273500
17,1561,Broward County,FL,Miami-Fort Lauderdale-West Palm Beach,12,11,12011,18,177400.0,172000.0,...,249400,250800,253100,255400,256800,258200,259900,261700,263200,264500
18,386,Bexar County,TX,San Antonio-New Braunfels,48,29,48029,19,127400.0,127300.0,...,172500,173100,173500,174100,174900,175600,176700,178000,179100,180100
19,2452,New York County,NY,New York-Newark-Jersey City,36,61,36061,20,959700.0,952000.0,...,1304200,1312600,1321500,1316900,1302700,1294800,1287400,1278800,1270900,1258900
20,3175,Philadelphia County,PA,Philadelphia-Camden-Wilmington,42,101,42101,21,114700.0,114300.0,...,145300,146700,148000,149200,150300,151300,152400,154100,156100,158400
21,1510,Alameda County,CA,San Francisco-Oakland-Hayward,6,1,06001,22,477500.0,473200.0,...,862300,865800,870900,872900,870500,870800,875100,878400,877400,873100
22,2801,Middlesex County,MA,Boston-Cambridge-Newton,25,17,25017,23,368200.0,368800.0,...,526200,527700,531100,534900,537500,539100,539700,540300,542200,545300
23,2046,Suffolk County,NY,New York-Newark-Jersey City,36,103,36103,24,369400.0,367000.0,...,381400,381500,379200,376700,376100,377400,380500,384600,388700,393500
24,3017,Sacramento County,CA,Sacramento--Roseville--Arden-Arcade,6,67,06067,25,231900.0,229800.0,...,355200,354700,355800,358100,360700,362400,363100,364000,365400,366700
25,401,Bronx County,NY,New York-Newark-Jersey City,36,5,36005,26,336200.0,330800.0,...,399900,406800,412400,416300,418700,420900,423400,426600,429600,432200
26,1252,Nassau County,NY,New York-Newark-Jersey City,36,59,36059,27,425200.0,421400.0,...,515500,519700,523000,527000,529700,529800,531200,535400,539900,541900
27,2993,Palm Beach County,FL,Miami-Fort Lauderdale-West Palm Beach,12,99,12099,28,195100.0,190900.0,...,263600,264700,266300,268200,270100,271800,273400,274800,275700,277000
28,2241,Cuyahoga County,OH,Cleveland-Elyria,39,35,39035,29,113500.0,113200.0,...,123700,124300,125100,125300,125200,125500,126100,127200,128400,129300
29,3165,Hillsborough County,FL,Tampa-St. Petersburg-Clearwater,12,57,12057,30,158300.0,155200.0,...,211100,212000,212900,213700,214600,215600,216600,218100,219900,221100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942,1867,Lincoln County,KS,NaN,20,105,20105,1943,NaN,NaN,...,47800,48100,48500,48600,48600,48700,48700,48600,48400,48300
1943,1245,Morton County,KS,NaN,20,129,20129,1944,NaN,NaN,...,87000,86800,86800,86900,86900,86800,86900,87100,87200,87100
1944,2286,Franklin County,NE,NaN,31,61,31061,1945,NaN,NaN,...,48500,48600,48900,49400,50100,51000,52200,53400,54700,56000
1945,257,Ness County,KS,NaN,20,135,20135,1946,NaN,NaN,...,60500,60400,60400,60300,60300,60300,60400,60500,60500,60500
1946,1730,Granite County,MT,NaN,30,39,30039,1947,NaN,NaN,...,181200,181200,180600,179700,179500,179600,179200,178900,179200,179700
1947,1125,Jewell County,KS,NaN,20,89,20089,1948,NaN,NaN,...,44300,44200,44200,44200,44300,44500,44600,44500,44400,44500
1948,1687,Edwards County,KS,NaN,20,47,20047,1949,NaN,NaN,...,40700,40700,40700,40500,40300,40200,40200,40200,40300,40400
1949,753,Trego County,KS,NaN,20,195,20195,1950,NaN,NaN,...,67400,67500,67500,67400,67100,67200,67500,67700,67600,67600
1950,1665,Decatur County,KS,NaN,20,39,20039,1951,NaN,NaN,...,58500,58600,58600,58400,58300,58200,58300,58400,58400,58500
1951,71,Elk County,KS,NaN,20,49,20049,1952,NaN,NaN,...,34300,34400,34400,34500,34600,34600,34600,34500,34400,34400
1952,434,Chase County,KS,NaN,20,17,20017,1953,NaN,NaN,...,59200,59200,59200,59100,58700,58400,58400,58700,58900,59100
1953,165,Gove County,KS,NaN,20,63,20063,1954,NaN,NaN,...,70300,70400,70500,70300,70200,70200,70400,70500,70500,70600
1954,2319,Hamilton County,KS,NaN,20,75,20075,1955,NaN,NaN,...,92500,92600,92700,92400,91900,91900,92100,92300,92400,92600
1955,1048,Graham County,KS,NaN,20,65,20065,1956,NaN,NaN,...,62100,62100,62100,61900,61600,61600,61700,61900,62000,62100
1956,583,Kiowa County,KS,NaN,20,97,20097,1957,NaN,NaN,...,87800,87800,87900,87700,87700,87800,88100,88100,88000,88000
1957,1994,Rawlins County,KS,NaN,20,153,20153,1958,NaN,NaN,...,84200,84000,84000,84000,83700,83600,83900,84200,84200,84000
1958,2499,Renville County,ND,Minot,38,75,38075,1959,NaN,NaN,...,123600,119900,116100,113800,113400,114300,116400,117500,117700,118500
1959,1667,Dickens County,TX,NaN,48,125,48125,1960,NaN,NaN,...,53800,53700,53700,53800,53400,53200,53100,53200,53500,53700
1960,2094,Wichita County,KS,NaN,20,203,20203,1961,NaN,NaN,...,86100,86300,86600,86300,85900,85700,86000,86200,86400,86700
1961,442,Clark County,KS,NaN,20,25,20025,1962,NaN,NaN,...,54300,54200,54200,54200,54400,54600,54800,54700,54700,54600
1962,3169,Judith Basin County,MT,NaN,30,45,30045,1963,NaN,NaN,...,168500,167200,166100,167400,169800,170300,171900,175500,178500,178700
1963,476,Deuel County,NE,NaN,31,49,31049,1964,NaN,NaN,...,64800,64600,64700,65400,66500,68100,70000,72300,75100,78000
1964,2346,Hodgeman County,KS,NaN,20,83,20083,1965,NaN,NaN,...,63600,63600,63500,63300,63200,63300,63400,63300,63300,63500
1965,2621,Armstrong County,TX,Amarillo,48,11,48011,1966,NaN,NaN,...,84100,84300,84600,84500,84200,84100,84200,84300,84600,84900
1966,2220,Comanche County,KS,NaN,20,33,20033,1967,NaN,NaN,...,38400,38600,38700,38800,38800,38500,38200,38100,38200,38300
1967,1649,Daniels County,MT,NaN,30,19,30019,1968,NaN,NaN,...,152600,152200,151700,151700,151900,152300,152500,152300,152100,151900
1968,230,Lane County,KS,NaN,20,101,20101,1969,NaN,NaN,...,60800,60900,61000,60800,60600,60600,60700,60900,61100,61200
1969,569,Irion County,TX,San Angelo,48,235,48235,1970,NaN,NaN,...,123400,123100,123200,123500,123400,123300,123300,123400,123700,124000
1970,1978,Prairie County,MT,NaN,30,79,30079,1971,NaN,NaN,...,109400,109300,108700,108600,108900,109300,109400,109200,109000,108800
1971,1648,Daggett County,UT,NaN,49,9,49009,1972,NaN,NaN,...,282300,282200,281600,280600,280200,280400,280700,281300,281600,281600

In [6]:
yr = '2009'
while int(yr) < 2019:
    yr_col = [col for col in df_zillow if col.startswith(yr)]
    df_zillow["Avg_Price"+yr] = ""
    for index, row in df_zillow.iterrows():
        avg = row.loc[yr_col].mean(axis=0)
        df_zillow.loc[index, "Avg_Price"+yr] = avg
    yr=str(int(yr)+1)
# df_zillow.head()

In [7]:
# Remove extra month columns

yr = '2009'
while int(yr) < 2019:
    df_zillow = df_zillow.drop(df_zillow.filter(like=yr+"-"), axis=1)
    yr=str(int(yr)+1)
    
df_zillow

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,FIPS,SizeRank,Avg_Price2009,Avg_Price2010,Avg_Price2011,Avg_Price2012,Avg_Price2013,Avg_Price2014,Avg_Price2015,Avg_Price2016,Avg_Price2017,Avg_Price2018
0,3101,Los Angeles County,CA,Los Angeles-Long Beach-Anaheim,6,37,06037,1,394467,388942,364758,361508,417183,458633,489950,529350,569558,608025
1,139,Cook County,IL,Chicago-Naperville-Elgin,17,31,17031,2,210442,191125,167692,156833,165842,179042,189400,199492,210517,220667
2,1090,Harris County,TX,Houston-The Woodlands-Sugar Land,48,201,48201,3,130308,128825,123667,122000,126942,136392,148525,162675,173267,183533
3,2402,Maricopa County,AZ,Phoenix-Mesa-Scottsdale,4,13,04013,4,170608,151150,135842,149925,179450,196083,209417,227683,243775,262150
4,2841,San Diego County,CA,San Diego-Carlsbad,6,73,06073,5,372983,374500,352758,355183,412025,449642,475467,510642,549025,585200
5,1286,Orange County,CA,Los Angeles-Long Beach-Anaheim,6,59,06059,6,495808,494042,463308,461983,541833,583800,613350,647775,681825,716075
6,581,Kings County,NY,New York-Newark-Jersey City,36,47,36047,7,475600,462075,474550,483225,518583,573317,630075,670667,727475,779033
7,2964,Miami-Dade County,FL,Miami-Fort Lauderdale-West Palm Beach,12,86,12086,8,176292,147683,141842,149375,168092,194433,221833,248683,274825,294550
8,978,Dallas County,TX,Dallas-Fort Worth-Arlington,48,113,48113,9,119792,117133,112458,110917,114125,121500,130250,146667,175475,197033
9,1347,Queens County,NY,New York-Newark-Jersey City,36,81,36081,10,431233,419458,412025,404500,430525,467283,501825,542467,587508,630592
10,2832,Riverside County,CA,Riverside-San Bernardino-Ontario,6,65,06065,11,222492,213975,205158,206858,247450,283967,303108,324592,347642,372183
11,3250,San Bernardino County,CA,Riverside-San Bernardino-Ontario,6,71,06071,12,197125,184625,174883,175808,209025,246933,265375,287117,314375,338792
12,445,Clark County,NV,Las Vegas-Henderson-Paradise,32,3,32003,13,162583,139458,125375,125983,153692,178433,192108,207533,232183,265042
13,207,King County,WA,Seattle-Tacoma-Bellevue,53,33,53033,14,358600,336517,312500,316733,355317,387525,431292,493758,574942,625767
14,791,Wayne County,MI,Detroit-Warren-Dearborn,26,163,26163,15,56041.7,35266.7,27533.3,28025,33275,40133.3,49216.7,54783.3,60450,74116.7
15,2049,Tarrant County,TX,Dallas-Fort Worth-Arlington,48,439,48439,16,131958,131025,126458,125058,129392,137067,146858,163833,183650,202533
16,3136,Santa Clara County,CA,San Jose-Sunnyvale-Santa Clara,6,85,06085,17,594050,594542,565550,600617,711417,787058,892800,957675,1.06342e+06,1.27028e+06
17,1561,Broward County,FL,Miami-Fort Lauderdale-West Palm Beach,12,11,12011,18,151867,134283,126000,126567,142192,163525,181142,203700,231675,255317
18,386,Bexar County,TX,San Antonio-New Braunfels,48,29,48029,19,125650,125142,122725,123083,125600,131108,139358,148600,162175,174867
19,2452,New York County,NY,New York-Newark-Jersey City,36,61,36061,20,910942,881350,903942,945142,1.01738e+06,1.16241e+06,1.24182e+06,1.3015e+06,1.32044e+06,1.29565e+06
20,3175,Philadelphia County,PA,Philadelphia-Camden-Wilmington,42,101,42101,21,113333,113233,106567,101992,100550,105525,109558,118308,134758,149750
21,1510,Alameda County,CA,San Francisco-Oakland-Hayward,6,1,06001,22,453408,445583,411683,422358,521292,598875,673525,729225,788508,867342
22,2801,Middlesex County,MA,Boston-Cambridge-Newton,25,17,25017,23,363042,365633,354650,361450,385692,411050,432692,460442,501592,533883
23,2046,Suffolk County,NY,New York-Newark-Jersey City,36,103,36103,24,357833,348833,328617,322650,330075,338033,341333,351942,370000,381592
24,3017,Sacramento County,CA,Sacramento--Roseville--Arden-Arcade,6,67,06067,25,218483,205217,181092,181683,230400,260725,280200,307358,337817,359533
25,401,Bronx County,NY,New York-Newark-Jersey City,36,5,36005,26,314883,312317,295767,282542,305992,318900,324300,328875,367975,413550
26,1252,Nassau County,NY,New York-Newark-Jersey City,36,59,36059,27,409258,402475,385042,378242,389183,412592,431617,454467,487108,525550
27,2993,Palm Beach County,FL,Miami-Fort Lauderdale-West Palm Beach,12,99,12099,28,174775,158308,145033,143467,158950,182342,208108,231825,251725,268942
28,2241,Cuyahoga County,OH,Cleveland-Elyria,39,35,39035,29,110517,109200,101100,95458.3,96633.3,98966.7,100667,107867,117100,125500
29,3165,Hillsborough County,FL,Tampa-St. Petersburg-Clearwater,12,57,12057,30,143075,128642,115775,116908,126783,141392,153375,172067,195233,214217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942,1867,Lincoln County,KS,NaN,20,105,20105,1943,NaN,63680,59025,56141.7,55450,53100,51050,47450,48233.3,48408.3
1943,1245,Morton County,KS,NaN,20,129,20129,1944,NaN,64060,68108.3,63900,64316.7,64533.3,72316.7,88000,93716.7,86983.3
1944,2286,Franklin County,NE,NaN,31,61,31061,1945,NaN,37440,36125,36766.7,38116.7,40508.3,41808.3,42541.7,47991.7,50841.7
1945,257,Ness County,KS,NaN,20,135,20135,1946,NaN,69320,67858.3,64800,63508.3,62266.7,62250,62858.3,63816.7,60450
1946,1730,Granite County,MT,NaN,30,39,30039,1947,NaN,143460,138517,139233,145317,151608,154142,158892,169225,179983
1947,1125,Jewell County,KS,NaN,20,89,20089,1948,NaN,50970,47083.3,46958.3,46625,45341.7,43541.7,41616.7,44866.7,44408.3
1948,1687,Edwards County,KS,NaN,20,47,20047,1949,NaN,56590,55083.3,50608.3,48100,45041.7,46233.3,49258.3,44725,40433.3
1949,753,Trego County,KS,NaN,20,195,20195,1950,NaN,71920,68108.3,65041.7,65008.3,66166.7,67241.7,66316.7,68541.7,67466.7
1950,1665,Decatur County,KS,NaN,20,39,20039,1951,NaN,56750,54050,54450,55316.7,56216.7,60491.7,63908.3,62666.7,58450
1951,71,Elk County,KS,NaN,20,49,20049,1952,NaN,60520,60858.3,57200,52766.7,42916.7,39200,35083.3,34200,34433.3
1952,434,Chase County,KS,NaN,20,17,20017,1953,NaN,69590,67208.3,65383.3,63700,61108.3,60975,60675,60750,58941.7
1953,165,Gove County,KS,NaN,20,63,20063,1954,NaN,71100,69058.3,67383.3,65358.3,66341.7,69533.3,69991.7,73275,70416.7
1954,2319,Hamilton County,KS,NaN,20,75,20075,1955,NaN,71000,70208.3,70116.7,70250,72358.3,79608.3,91483.3,97316.7,92416.7
1955,1048,Graham County,KS,NaN,20,65,20065,1956,NaN,64380,62583.3,61108.3,60900,61458.3,63266.7,63391.7,65241.7,61933.3
1956,583,Kiowa County,KS,NaN,20,97,20097,1957,NaN,83590,82750,80941.7,82283.3,82983.3,82783.3,86191.7,89233.3,87925
1957,1994,Rawlins County,KS,NaN,20,153,20153,1958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89058.3,90425,83975
1958,2499,Renville County,ND,Minot,38,75,38075,1959,NaN,NaN,NaN,NaN,NaN,106792,106642,110767,124608,118983
1959,1667,Dickens County,TX,NaN,48,125,48125,1960,NaN,38050,37850,37591.7,38141.7,41033.3,43025,45916.7,50600,53500
1960,2094,Wichita County,KS,NaN,20,203,20203,1961,NaN,74170,72758.3,71000,69950,71908.3,78575,93458.3,97983.3,86350
1961,442,Clark County,KS,NaN,20,25,20025,1962,NaN,54680,59666.7,56808.3,56875,52391.7,51483.3,54358.3,56525,54458.3
1962,3169,Judith Basin County,MT,NaN,30,45,30045,1963,NaN,128980,131833,134733,139267,140483,143583,155008,165417,171042
1963,476,Deuel County,NE,NaN,31,49,31049,1964,NaN,45870,45850,46900,48183.3,49966.7,51783.3,57633.3,64975,68316.7
1964,2346,Hodgeman County,KS,NaN,20,83,20083,1965,NaN,65930,65283.3,62808.3,61450,61150,63491.7,65616.7,66366.7,63466.7
1965,2621,Armstrong County,TX,Amarillo,48,11,48011,1966,NaN,69920,69483.3,70750,73058.3,76991.7,80041.7,84475,87533.3,84408.3
1966,2220,Comanche County,KS,NaN,20,33,20033,1967,NaN,NaN,53350,51800,51958.3,44675,40741.7,41683.3,39125,38441.7
1967,1649,Daniels County,MT,NaN,30,19,30019,1968,NaN,128940,129067,129375,132150,133183,137092,144983,152642,152067
1968,230,Lane County,KS,NaN,20,101,20101,1969,NaN,65270,63741.7,61200,59916.7,58975,60525,63450,65016.7,60925
1969,569,Irion County,TX,San Angelo,48,235,48235,1970,NaN,84070,83358.3,86341.7,90575,96491.7,104817,112992,121058,123508
1970,1978,Prairie County,MT,NaN,30,79,30079,1971,NaN,107980,108492,109658,114400,116517,119083,123708,116392,109008
1971,1648,Daggett County,UT,NaN,49,9,49009,1972,NaN,203140,192808,195800,210533,224708,236633,261958,277558,281442

In [11]:
df_zillow1 = pd.wide_to_long(df_zillow, stubnames='Avg_Price', i=['RegionName','State','FIPS'], j='Year')
df_zillow1 = df_zillow1.drop(['SizeRank','RegionID','StateCodeFIPS','MunicipalCodeFIPS','Metro'], axis=1)
df_zillow1

                                    Avg_Price
RegionName         State FIPS  Year
Los Angeles County CA    06037 2009    394467
                               2010    388942
                               2011    364758
                               2012    361508
                               2013    417183
                               2014    458633
                               2015    489950
                               2016    529350
                               2017    569558
                               2018    608025
Cook County        IL    17031 2009    210442
                               2010    191125
                               2011    167692
                               2012    156833
                               2013    165842
                               2014    179042
                               2015    189400
                               2016    199492
                               2017    210517
                               2018    220667
Harris County      TX    48201 2009    130308
                               2010    128825
                               2011    123667
                               2012    122000
                               2013    126942
                               2014    136392
                               2015    148525
                               2016    162675
                               2017    173267
                               2018    183533
...                                       ...
Irion County       TX    48235 2009       NaN
                               2010     84070
                               2011   83358.3
                               2012   86341.7
                               2013     90575
                               2014   96491.7
                               2015    104817
                               2016    112992
                               2017    121058
                               2018    123508
Prairie County     MT    30079 2009       NaN
                               2010    107980
                               2011    108492
                               2012    109658
                               2013    114400
                               2014    116517
                               2015    119083
                               2016    123708
                               2017    116392
                               2018    109008
Daggett County     UT    49009 2009       NaN
                               2010    203140
                               2011    192808
                               2012    195800
                               2013    210533
                               2014    224708
                               2015    236633
                               2016    261958
                               2017    277558
                               2018    281442

[19720 rows x 1 columns]

In [12]:
df_zillow1.reset_index()

               RegionName State   FIPS  Year Avg_Price
0      Los Angeles County    CA  06037  2009    394467
1      Los Angeles County    CA  06037  2010    388942
2      Los Angeles County    CA  06037  2011    364758
3      Los Angeles County    CA  06037  2012    361508
4      Los Angeles County    CA  06037  2013    417183
5      Los Angeles County    CA  06037  2014    458633
6      Los Angeles County    CA  06037  2015    489950
7      Los Angeles County    CA  06037  2016    529350
8      Los Angeles County    CA  06037  2017    569558
9      Los Angeles County    CA  06037  2018    608025
10            Cook County    IL  17031  2009    210442
11            Cook County    IL  17031  2010    191125
12            Cook County    IL  17031  2011    167692
13            Cook County    IL  17031  2012    156833
14            Cook County    IL  17031  2013    165842
15            Cook County    IL  17031  2014    179042
16            Cook County    IL  17031  2015    189400
17            Cook County    IL  17031  2016    199492
18            Cook County    IL  17031  2017    210517
19            Cook County    IL  17031  2018    220667
20          Harris County    TX  48201  2009    130308
21          Harris County    TX  48201  2010    128825
22          Harris County    TX  48201  2011    123667
23          Harris County    TX  48201  2012    122000
24          Harris County    TX  48201  2013    126942
25          Harris County    TX  48201  2014    136392
26          Harris County    TX  48201  2015    148525
27          Harris County    TX  48201  2016    162675
28          Harris County    TX  48201  2017    173267
29          Harris County    TX  48201  2018    183533
...                   ...   ...    ...   ...       ...
19690        Irion County    TX  48235  2009       NaN
19691        Irion County    TX  48235  2010     84070
19692        Irion County    TX  48235  2011   83358.3
19693        Irion County    TX  48235  2012   86341.7
19694        Irion County    TX  48235  2013     90575
19695        Irion County    TX  48235  2014   96491.7
19696        Irion County    TX  48235  2015    104817
19697        Irion County    TX  48235  2016    112992
19698        Irion County    TX  48235  2017    121058
19699        Irion County    TX  48235  2018    123508
19700      Prairie County    MT  30079  2009       NaN
19701      Prairie County    MT  30079  2010    107980
19702      Prairie County    MT  30079  2011    108492
19703      Prairie County    MT  30079  2012    109658
19704      Prairie County    MT  30079  2013    114400
19705      Prairie County    MT  30079  2014    116517
19706      Prairie County    MT  30079  2015    119083
19707      Prairie County    MT  30079  2016    123708
19708      Prairie County    MT  30079  2017    116392
19709      Prairie County    MT  30079  2018    109008
19710      Daggett County    UT  49009  2009       NaN
19711      Daggett County    UT  49009  2010    203140
19712      Daggett County    UT  49009  2011    192808
19713      Daggett County    UT  49009  2012    195800
19714      Daggett County    UT  49009  2013    210533
19715      Daggett County    UT  49009  2014    224708
19716      Daggett County    UT  49009  2015    236633
19717      Daggett County    UT  49009  2016    261958
19718      Daggett County    UT  49009  2017    277558
19719      Daggett County    UT  49009  2018    281442

[19720 rows x 5 columns]

In [13]:
df_zillow1.to_csv('resources/Zillow_Data/Avg_Home_County.csv')