In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [5]:
# Pull in file 
merged_df = pd.read_csv('Resources/clean_merge.csv')

merged_df

FileNotFoundError: [Errno 2] File b'Resources/clean_merge.csv' does not exist: b'Resources/clean_merge.csv'

In [ ]:
merged_df['Industry'] = merged_df['Industry'].str.replace('\d+', '')
merged_df['Industry'] = merged_df['Industry'].str.strip()

merged_df

In [ ]:
industry_group = merged_df.groupby(['Year', 'State', 'Industry'])
avg_employ = industry_group["Annual Average Employment"].mean()
avg_employ = pd.DataFrame(avg_employ).reset_index()
avg_employ.head()

In [12]:
avg_year = avg_employ.groupby(['Year','Industry'])
avg_EmployYear = avg_year['Annual Average Employment'].mean()

avg_EmployYear = pd.DataFrame(avg_EmployYear).reset_index()
avg_EmployYear

     Year                              Industry  Annual Average Employment
0    2009                          Construction                3488.720373
1    2009         Education and health services               12211.499511
2    2009                  Financial activities                4867.877481
3    2009                       Goods-producing               10045.821945
4    2009                           Information                1833.240260
5    2009               Leisure and hospitality                9080.502434
6    2009                         Manufacturing                5780.057360
7    2009          Natural resources and mining                 729.457297
8    2009                        Other services                3588.625674
9    2009    Professional and business services               11595.325264
10   2009                     Service-providing               57161.337521
11   2009                 Total, all industries               33259.130151
12   2009  Trade, transportation, and utilities               13774.768460
13   2009                          Unclassified                 207.613311
14   2010                          Construction                3165.027525
15   2010         Education and health services               12442.481803
16   2010                  Financial activities                4732.404831
17   2010                       Goods-producing                9538.889858
18   2010                           Information                1778.321041
19   2010               Leisure and hospitality                9172.413114
20   2010                         Manufacturing                5587.068786
21   2010          Natural resources and mining                 732.951626
22   2010                        Other services                3592.750630
23   2010    Professional and business services               11664.380247
24   2010                     Service-providing               57168.488705
25   2010                 Total, all industries               33113.790308
26   2010  Trade, transportation, and utilities               13652.382136
27   2010                          Unclassified                 186.126398
28   2011                          Construction                3163.296644
29   2011         Education and health services               12713.551141
..    ...                                   ...                        ...
110  2016  Trade, transportation, and utilities               15012.339318
111  2016                          Unclassified                 253.272896
112  2017                          Construction                3726.980707
113  2017         Education and health services               14708.683634
114  2017                  Financial activities                5084.944410
115  2017                       Goods-producing               10794.198182
116  2017                           Information                1780.627113
117  2017               Leisure and hospitality               11086.464377
118  2017                         Manufacturing                5941.972794
119  2017          Natural resources and mining                 769.417989
120  2017                        Other services                3831.517997
121  2017    Professional and business services               13843.151185
122  2017                     Service-providing               65665.703069
123  2017                 Total, all industries               36992.685293
124  2017  Trade, transportation, and utilities               15154.729989
125  2017                          Unclassified                 214.733912
126  2018                          Construction                4217.936802
127  2018         Education and health services               15044.292510
128  2018                  Financial activities                5127.266237
129  2018                       Goods-producing               11086.153487
130  2018                           Information                1810.993833
131  2018               Leisure and hospitality               11310.928220
132  2018                         Manufacturing                6052.972900
133  2018          Natural resources and mining                 789.375865
134  2018                        Other services                3914.774747
135  2018    Professional and business services               14140.481069
136  2018                     Service-providing               66571.379477
137  2018                 Total, all industries               37524.862163
138  2018  Trade, transportation, and utilities               15260.013177
139  2018                          Unclassified                  77.460976

[140 rows x 3 columns]

In [13]:
avg_EmployYear.min()

Year                                 2009
Industry                     Construction
Annual Average Employment          77.461
dtype: object

In [14]:
avg_EmployYear.max()

Year                                 2018
Industry                     Unclassified
Annual Average Employment         66571.4
dtype: object

In [15]:
construction_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Construction", "Annual Average Employment"]
education_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Education and health services", "Annual Average Employment"]
finance_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Financial activities", "Annual Average Employment"]
goods_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Goods-producing", "Annual Average Employment"]
information_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Information", "Annual Average Employment"]
leisure_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Leisure and hospitality", "Annual Average Employment"]
manufacturing_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Manufacturing", "Annual Average Employment"]
natural_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Natural resources and mining", "Annual Average Employment"]
other_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Other services", "Annual Average Employment"]
professional_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Professional and business services", "Annual Average Employment"]
service_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Service-providing", "Annual Average Employment"]
total_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Total, all industries", "Annual Average Employment"]
trade_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Trade, transportation, and utilities", "Annual Average Employment"]
unclassified_avg = avg_EmployYear.loc[avg_EmployYear['Industry'] == "Unclassified", "Annual Average Employment"]

years = [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]

In [2]:
construction = plt.plot(years, construction_avg, color="red", label="Construction")
education = plt.plot(years, education_avg, color="maroon", label="Education and health services")
finance = plt.plot(years, finance_avg, color="yellow", label="Financial activities")
goods = plt.plot(years, goods_avg, color="lime", label="Goods-producing")
information = plt.plot(years, information_avg, color="green", label="Information")
leisure = plt.plot(years, leisure_avg, color="magenta", label="Leisure and hospitality")
manufacturing = plt.plot(years, manufacturing_avg, color="purple", label="Manufacturing")
natural = plt.plot(years, natural_avg, color="cyan", label="Natural resources and mining")
other = plt.plot(years, other_avg, color="teal", label="Other services")
professional = plt.plot(years, professional_avg, color="blue", label="Professional and business services")
service = plt.plot(years, service_avg, color="navy", label="Service-providing")
total = plt.plot(years, total_avg, color="silver", label="Total, all industries")
trade = plt.plot(years, trade_avg, color="gray", label="Trade, transportation, and utilites")
unclassified = plt.plot(years, unclassified_avg, color="black", label="Unclassified")

plt.xlabel("Year")
plt.ylabel("Annual Average Employment")

tick_locations = years
plt.xticks(np.arange(2009, 2019, 1))
plt.yticks(np.arange(0, 70000, 5000))

#plt.legend(['finance', 'professional'], loc="best")
#plt.legend(['construction', 'education', 'finance', 'goods', 'information', 'leisure', 'manufacturing', 'natural', 'other', 'professional', 'service', 'total', 'trade', 'unclassified'], loc="best")
#plt.legend('Construction', 'Education and health services', 'Financial activities', 'Goods-proudcing', 'Information', 'Leisure and hospitality', 'Manufacturing', 'Natural resources and mining', 'Other services', 'Professional and business services', 'Service-providing', 'Total', 'Trade, transportation, and utilites', 'Unclassified')
plt.show()

NameError: name 'plt' is not defined

In [18]:
plt.savefig("Images/Annual_employChange.png")
plt.show()