In [1]:
import pandas as pd
import numpy as np

import plotly

import plotly.graph_objs as go


import plotly.offline as offline

from plotly.graph_objs import *

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import plotly.graph_objects as go

init_notebook_mode(connected=True)

In [2]:
merge_csv = "Resources/merged_data/clean_merge2.csv"
merged_df = pd.read_csv(merge_csv, encoding="ISO-8859-1", low_memory=False, dtype={"FIPS": str})

In [3]:
merged_df.head()

,FIPS,Year,RegionName,State,Industry,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages,Annual Average Pay,Avg_Price
0,01001,2009,Autauga County,AL,Federal Government,15,100,4476122,44873,144408.333333
1,01001,2009,Autauga County,AL,State Government,16,519,18717293,36093,144408.333333
2,01001,2009,Autauga County,AL,Local Government,32,1995,67539151,33857,144408.333333
3,01001,2009,Autauga County,AL,Goods-producing,159,1842,91335147,49580,144408.333333
4,01001,2009,Autauga County,AL,Natural resources and mining,23,197,5506289,28022,144408.333333

In [4]:
#County_avg = merged_df.groupby(['Year','FIPS']).agg({'Avg_Price':'mean'})
County_avg = merged_df.groupby(['Year','FIPS']).mean()
#County_avg = merged_df.groupby(['Year','FIPS'])*merged_df.shape[1],axis=1).mean()
County_avg.head(100)

            Annual Average Establishment Count  Annual Average Employment  \
Year FIPS
2009 01001                          113.000000                1293.066667
     01003                          692.266667                7297.266667
     01009                           99.333333                1009.466667
     01017                           76.733333                 872.200000
     01019                           49.866667                 563.266667
     01021                           99.000000                 986.200000
     01031                          138.266667                1790.200000
     01033                          173.866667                2434.533333
     01045                          114.333333                2056.733333
     01047                          116.800000                1612.333333
     01049                          157.133333                2520.533333
     01051                          163.600000                2078.800000
     01055                          278.400000                4125.266667
     01069                          394.800000                5732.666667
     01073                         2391.733333               41127.200000
     01077                          265.133333                3594.933333
     01081                          340.533333                5374.400000
     01083                          171.866667                2331.733333
     01089                         1153.333333               21277.733333
     01097                         1288.333333               20319.466667
     01101                          829.066667               15110.000000
     01103                          364.133333                5561.466667
     01109                           95.066667                1619.666667
     01113                          115.400000                1478.933333
     01115                          175.866667                1890.266667
     01117                          639.600000                8922.000000
     01121                          178.000000                3127.066667
     01123                          111.400000                1569.666667
     01125                          568.400000                9524.466667
     01127                          188.400000                2227.866667
...                                        ...                        ...
     05113                           73.866667                 755.666667
     05115                          234.466667                3170.000000
     05119                         1974.466667               28965.733333
     05121                           54.733333                 570.733333
     05125                          246.066667                2451.333333
     05131                          513.200000                8585.733333
     05135                           56.800000                 422.000000
     05139                          181.333333                2269.200000
     05143                          740.800000               10839.933333
     05145                          242.533333                3087.133333
     05149                           57.000000                 751.333333
     06001                         6571.875000               73725.562500
     06005                          127.250000                1220.312500
     06007                          953.937500                8068.812500
     06009                          159.375000                 828.250000
     06011                           96.625000                 876.375000
     06013                         3648.250000               37119.000000
     06017                          618.187500                5375.187500
     06019                         3688.187500               37758.625000
     06021                          138.687500                 850.812500
     06023                          627.500000                4992.125000
     06025                          863.687500                6050.875000
     06027                           87.687500                 747.500000
     06029                         2170.437500               29905.125000
     06031                          428.000000                4348.250000
     06033                          349.687500                1573.687500
     06037                        52410.437500              454939.250000
     06039                          462.687500                4888.875000
     06041                         1433.062500               11951.500000
     06043                           61.125000                 536.312500

            Annual Total Wages  Annual Average Pay      Avg_Price
Year FIPS
2009 01001        3.977403e+07        34673.666667  144408.333333
     01003        2.198155e+08        34206.533333  176875.000000
     01009        2.899548e+07        30891.000000  128516.666667
     01017        2.639403e+07        32101.400000   55033.333333
     01019        1.598982e+07        30002.733333   97183.333333
     01021        2.849764e+07        30371.133333   98800.000000
     01031        5.021076e+07        30739.200000  120900.000000
     01033        8.733275e+07        38032.400000   90708.333333
     01045        9.206689e+07        38416.000000   86233.333333
     01047        5.042783e+07        32667.800000   55583.333333
     01049        7.858225e+07        33902.400000   89300.000000
     01051        6.172091e+07        33287.733333  171050.000000
     01055        1.333561e+08        34727.733333   97391.666667
     01069        1.966679e+08        34932.866667  142558.333333
     01073        1.886477e+09        49983.000000  111850.000000
     01077        1.022743e+08        32804.666667  102191.666667
     01081        1.692584e+08        35563.000000  170075.000000
     01083        8.639104e+07        38971.466667  135708.333333
     01089        1.042720e+09        46610.866667            NaN
     01097        7.923965e+08        43595.866667  113783.333333
     01101        5.896388e+08        40008.266667  100725.000000
     01103        2.050496e+08        36957.066667            NaN
     01109        5.175738e+07        32230.066667  118108.333333
     01113        4.578959e+07        27351.533333  106558.333333
     01115        5.738331e+07        32984.266667  146150.000000
     01117        3.862604e+08        44152.266667  184308.333333
     01121        1.192137e+08        36924.533333  100408.333333
     01123        4.733624e+07        32226.666667  106233.333333
     01125        3.610451e+08        41154.800000  139600.000000
     01127        7.058170e+07        34765.600000   51250.000000
...                        ...                 ...            ...
     05113        1.850923e+07        26146.800000   83858.333333
     05115        1.005764e+08        32925.200000   95783.333333
     05119        1.226063e+09        46901.533333  122041.666667
     05121        1.343258e+07        25020.400000            NaN
     05125        7.145172e+07        33410.866667  130166.666667
     05131        2.977317e+08        38516.400000  104408.333333
     05135        1.015203e+07        24032.800000   67341.666667
     05139        9.051932e+07        38995.933333   75791.666667
     05143        3.938902e+08        39793.800000  139533.333333
     05145        1.041859e+08        35096.400000   95075.000000
     05149        1.991955e+07        24624.266667   73091.666667
     06001        4.299566e+09        58718.500000  453408.333333
     06005        4.221556e+07        34973.375000  223541.666667
     06007        2.760284e+08        36315.437500  217525.000000
     06009        2.600093e+07        33673.937500  246658.333333
     06011        2.874266e+07        30908.250000  176191.666667
     06013        2.084456e+09        61566.625000  352466.666667
     06017        2.138504e+08        42539.875000  326883.333333
     06019        1.329293e+09        38574.875000  175558.333333
     06021        2.685536e+07        29793.312500  151583.333333
     06023        1.584421e+08        34937.062500  231691.666667
     06025        1.889609e+08        34464.812500  130575.000000
     06027        2.441830e+07        34972.000000  280475.000000
     06029        1.154149e+09        41434.875000  148166.666667
     06031        1.476036e+08        35583.562500  162775.000000
     06033        5.084931e+07        33527.937500  173308.333333
     06037        2.311865e+10        55108.687500  394466.666667
     06039        1.645686e+08        35685.062500  149825.000000
     06041        6.608830e+08        55869.562500  719600.000000
     06043        1.503323e+07        31095.375000  152900.000000

[100 rows x 5 columns]

In [ ]:
fig = go.Figure(go.Choroplethmapbox(geojson=counties, locations=merged_df.FIPS, z=merged_df.Avg_Price,
                                    colorscale="Viridis", zmin=0, zmax=12,
                                    marker_opacity=0.5, marker_line_width=0))
fig.update_layout(mapbox_style="carto-positron",
                  mapbox_zoom=3, mapbox_center = {"lat": 37.0902, "lon": -95.7129})
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [ ]:
data_slider = []

for year in merged_df.Year.unique():
        df_price = merged_df[(merged_df['Year']== year)]
        fig = go.Figure(go.Choroplethmapbox(geojson=counties, locations=df_price.FIPS, z=df_price.Avg_Price,
                                    colorscale="Viridis", zmin=0, zmax=12,
                                    marker_opacity=0.5, marker_line_width=0))
        fig.update_layout(mapbox_style="carto-positron",
                          mapbox_zoom=3, mapbox_center = {"lat": 37.0902, "lon": -95.7129})
        fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
        data_slider.append(fig) 
        fig.show()

In [ ]:
# scl = [[0.0, '#ffffff'],[0.2, '#ff9999'],[0.4, '#ff4d4d'], 
#        [0.6, '#ff1a1a'],[0.8, '#cc0000'],[1.0, '#4d0000']] 

# data_slider = []

# for year in merged_df.Year.unique():
    
#     df_price = merged_df[(merged_df['Year']== year)]

#     for col in df_price.columns:
#         df_price[col] = df_price[col].astype(str)

#     df_price['text'] = df_price['RegionName']#+'Avg_Price: 'df_price['Avg_Price']
    
#     data_one_year = dict(
#                         type='choropleth',
#                         locations = df_price['FIPS'],
#                         z=df_price['Avg_Price'].astype(float),
#                         #locationmode='USA-states',
#                         colorscale = scl,
#                         text = df_price['text'],
#                         )

#     data_slider.append(data_one_year)

In [ ]:
steps = []

for i in range(len(data_slider)):
    step = dict(method='restyle',
                args=['visible', [False] * len(data_slider)],
                label='Year {}'.format(i + 2009)) # label to be displayed for each step (year)
    step['args'][1][i] = True
    steps.append(step)
    
sliders = [dict(active=0, pad={"t": 1}, steps=steps)] 

# fig.update_layout(mapbox_style="carto-positron",
#                   mapbox_zoom=3, mapbox_center = {"lat": 37.0902, "lon": -95.7129})
# fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})

fig = dict(data=data_slider, layout=layout) 

plotly.offline.iplot(fig)

In [ ]:
# data = [ dict(
#             type='choropleth', # type of map-plot
#             colorscale = scl,
#             autocolorscale = False,
#             locations = df_price['FIPS'], # the column with the state
#             z = df_price['Avg_Price'].astype(float), # the variable I want to color-code
#             #locationmode = 'USA-states',
#             text = df_price['text'], # hover text
#             marker = dict(     # for the lines separating states
#                         line = dict (
#                                   color = 'rgb(255,255,255)', 
#                                   width = 2) ),               
#             colorbar = dict(
#                         title = "Average Price by County")
#             ) 
#        ]

# layout = dict(
#         title = year,
#         geo = dict(
#             scope='usa',
#             projection=dict( type='albers usa' ),

# #              showlakes = True,  # if you want to give color to the lakes

# #             lakecolor = 'rgb(73, 216, 230)'  
#             ),
#              )


# fig = dict( data=data, layout=layout )
# plotly.offline.iplot(fig)